FROM python:3.10-alpine

WORKDIR /app

RUN apk update && apk add --no-cache bash
RUN pip install --upgrade pip

ADD requirements requirements
RUN pip install --upgrade pip wheel setuptools -r requirements/requirements-dev.txt

# TODO we might want more debug mode functionality?
# RUN pip install debugpy=

COPY ./user_hasher/ /app/src
COPY ./tests/ /app/tests
COPY ./entrypoint_localhost.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh