replicaCount: 1

image:
  repository: nginx
  # tag: "1.16.0"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  name: foobar-service
  # type: ClusterIP
  type: NodePort
  # type: LoadBalancer
  port: 80
  targetPort: 80

env:
  name: foobar