# kubectl apply -f service.yaml

apiVersion: v1
kind: Service
metadata:
  name: hello-world-python-service-v1
spec:
  type: NodePort
  selector:
    app: hello-world-python
  ports:
  - port: 9000
    targetPort: 6000
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-python-service-v2
spec:
  type: LoadBalancer
  selector:
    app: hello-world-python
  ports:
  - port: 9001
    targetPort: 6000